executable              = /afs/cern.ch/user/m/marquezh/public/siwecal_k4sim/simulation/run_script/steer/runddsim_QGSP_BERT_SiWECAL_beam_mu-_100GeV_xy_1_1_sigx24.75_sigy13.75_sigE0.02.sh
log                     = /afs/cern.ch/user/m/marquezh/public/siwecal_k4sim/simulation/run_script/log/runddsim_QGSP_BERT_SiWECAL_beam_mu-_100GeV_xy_1_1_sigx24.75_sigy13.75_sigE0.02.log
output                  = /afs/cern.ch/user/m/marquezh/public/siwecal_k4sim/simulation/run_script/log/outfile_runddsim_QGSP_BERT_SiWECAL_beam_mu-_100GeV_xy_1_1_sigx24.75_sigy13.75_sigE0.02.txt
error                   = /afs/cern.ch/user/m/marquezh/public/siwecal_k4sim/simulation/run_script/log/errors_runddsim_QGSP_BERT_SiWECAL_beam_mu-_100GeV_xy_1_1_sigx24.75_sigy13.75_sigE0.02.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
+JobFlavour             = "tomorrow"
queue 1
