#!/usr/bin/env python3
"""Generate the SiPadHits readout block for a given number of tiled ASUs.

MultiSegmentation dispatches on the 'wafer' physVolID and needs one entry per
wafer, because every wafer has its own pair of offsets. With 3x3 ASUs that is 36
entries, which is not something to maintain by hand -- hence this script.

The grid inside a wafer is always the plain pixel pitch (Ecal_CellSizeX, the
active pad plus the inter-pad margin); only the offset changes, shifted by a
whole pad array so that the x/y fields come out as the GLOBAL pad indices over
the layer (0..31 for one ASU, 0..63 for 2x2, 0..95 for 3x3). Note the shift is
the pad array Ecal_NPadsPerWaferX*Ecal_CellSizeX, not the physical sensor size:
the segmentation lives in the frame of the sensitive volume, so the sensor's
inactive rim plays no part in it.

Usage:
    python make_readout.py [NASUsX] [NASUsY]

Paste the output over the <readout name="SiPadHits"> block of SND_compact.xml,
and set Ecal_NASUsX / Ecal_NASUsY to the same values.
"""
import sys

WAFERS_PER_ASU = 2   # per side, must match Ecal_NWafersX/Y
PADS_PER_WAFER = 16  # per side, must match Ecal_NPadsPerWaferX/Y


def readout(asus_x: int, asus_y: int) -> str:
    cols, rows = asus_x * WAFERS_PER_ASU, asus_y * WAFERS_PER_ASU
    # 'wafer' must hold cols*rows values; keep it last so the bit positions of
    # system/layer/slice/x/y never move.
    bits = max(1, (cols * rows - 1).bit_length())

    segs = []
    for w in range(cols * rows):
        gx, gy = w % cols, w // cols
        # offset = -(pad array - pitch)/2 - gx * (pads per wafer) * pitch
        ox = f"Ecal_SegOffsetX0-{gx}*Ecal_NPadsPerWaferX*Ecal_CellSizeX" if gx else "Ecal_SegOffsetX0"
        oy = f"Ecal_SegOffsetY0-{gy}*Ecal_NPadsPerWaferY*Ecal_CellSizeY" if gy else "Ecal_SegOffsetY0"
        segs.append(
            f'        <segmentation name="wafer{w}" type="TiledLayerGridXY" key_value="{w}"\n'
            f'                      grid_size_x="Ecal_CellSizeX" grid_size_y="Ecal_CellSizeY"\n'
            f'                      offset_x="{ox}"\n'
            f'                      offset_y="{oy}"\n'
            f'                      identifier_x="x" identifier_y="y" identifier_layer="layer"/>'
        )

    return (
        f'    <!-- {asus_x}x{asus_y} ASUs = {cols}x{rows} wafers = '
        f'{cols * PADS_PER_WAFER}x{rows * PADS_PER_WAFER} pads. '
        f'Generated by make_readout.py, do not edit by hand. -->\n'
        f'    <readout name="SiPadHits">\n'
        f'      <segmentation type="MultiSegmentation" key="wafer">\n'
        + "\n".join(segs)
        + f'\n      </segmentation>\n'
        f'      <id>system:8,layer:8,slice:5,x:9,y:9,wafer:{bits}</id>\n'
        f'    </readout>'
    )


if __name__ == "__main__":
    nx = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    ny = int(sys.argv[2]) if len(sys.argv) > 2 else nx
    print(readout(nx, ny))
